### PR TITLE
Added hardhat-etherscan support for Cronos Mainnet and Testnet

### PR DESCRIPTION
**Pull request by croyyds**
- [ ] Because this PR includes a **bug fix**, relevant tests have been included.
- [ ] Because this PR includes a **new feature**, the change was previously discussed on an Issue or with someone from the team.
- [x] I didn't do anything of this.

---

### CODE REVIEW

**Comment by calvinaco** [comment]
Hello @alcuadrado @fvictorio, nice to meet you.

This feature is wanted by the Cronos community members. May I know how we can push this changes forward into the repository? Any missing steps and I will be more than happy to help out.

Thank you!

**Comment by ihorbond** [comment]
Yes, very much needed

**Comment by fvictorio** [comment]
Hi, please read my comment [here](https://github.com/NomicFoundation/hardhat/pull/2441#issuecomment-1116382707). The tl;dr is that we are not adding new chains to the core of `hardhat-etherscan` anymore, but now there is a way to do it manually, and to abstract that process in a community plugin. Please let me know if you have any questions about this, I'd be happy to help with this.

**Comment by croyyds** [comment]
Hi @fvictorio , I did encounter some blockers while trying to integrate the new way of incorporating custom chains, and we do appreciate a lot your effort trying to solve the issues like [this](https://github.com/NomicFoundation/hardhat/pull/2661/commits/9191432b8a405e487ffb95e9b8356f0cbd85c546). However, the community is really looking forward to seeing support of Cronos on hardhat-etherscan as soon as possible. Would you do us a favour and approve this PR please. Very much appreciated!

**Pull request closed without merging**
