### PR TITLE
fix: use node v18 for hardhat-ledger

### PR DESCRIPTION
**Pull request by Wodann**

### CODE REVIEW

**Comment by Wodann** [comment]
@fvictorio why is the ledger test failing, whereas the other ones are not?

**Comment by fvictorio** [comment]
I have no idea why it was working before and then it stopped working. But the fix I sent is something we'll probably do in all packages: the build script runs the root's build script, and this is run before running the tests.

That being said, can you explain why is this change necessary? And why it's done only in `hh-ledger`?

**Comment by Wodann** [comment]
> That being said, can you explain why is this change necessary? And why it's done only in `hh-ledger`?

The change I made was to update the hardhat-ledger CI to require node 18. This was a change that was already done to all other CI workflows previously, as a bug existed in older node versions when marshalling a buffer of data.

**Comment by fvictorio** [comment]
> This was a change that was already done to all other CI workflows previously, as a bug existed in older node versions when marshalling a buffer of data.

Ah, sorry, I completely forgot about that.

**Review by fvictorio — APPROVED** [review]

**Pull request merged**
