### PR TITLE
feat(blockchain): add reservation of blocks

### PR DESCRIPTION
**Pull request by Wodann**

### CODE REVIEW

**Review by agostbiro — APPROVED** [review]
Thanks, looks good overall. Two questions:

- Can `reserve_blocks` have a default implementation in the trait? It looks like the two implementations are the same.
- Is this tested from the hardhat side? Would be good to have tests for edge cases.

Feel free to merge if these are not concerns.

**Comment by Wodann** [comment]
> - Can `reserve_blocks` have a default implementation in the trait? It looks like the two implementations are the same.

They are mostly the same, yes. I can see about moving shared code to a file.

> - Is this tested from the hardhat side? Would be good to have tests for edge cases.

Yes, at the moment most of our codebase relies on tests in Hardhat. Once we have released, we'll start porting over more tests so that we can test standalone.

**Comment by Wodann** [comment]
I tried splitting the shared code into a free function but ran into lifetime violations, so left the code as is for now. In the future, if we have a `trait BlockchainStorage`, we might be able to resolve it through a default implementation on the `trait Blockchain`

**Comment by Wodann** [comment]
CI is failing due to https://github.com/NomicFoundation/hardhat/actions/runs/6026825025/job/16350667120#step:9:3168

**Pull request merged**
