### PR TITLE
dotenv 10.0.0 doesn't load my .env file properly

### PR DESCRIPTION
**Pull request by samlaf**
dotenv was not loading my `.env` file properly, and only updating it to the latest version fixed it.

I haven't figured out the root cause of the problem though.
This stackoverflow answer (https://stackoverflow.com/a/70037859/4971151) suggests using
```
require('dotenv').config({path:__dirname+'/.env'})
```
instead of the `require('dotenv').config()` that hardhat is using, but I haven't gotten any problems with dotenv 16 so far, so seems like a cleaner approach.

my `tsconfig.json` file is
```
{
  "compilerOptions": {
    "declaration": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "module": "commonjs",
    "outDir": "dist",
    "resolveJsonModule": true,
    "strict": true,
    "target": "es2019"
  },
  "include": ["./scripts", "./test", "./typechain", "./deploy", "./lib"],
  "files": ["./hardhat.config.ts"]
}
```

- [ ] Because this PR includes a **bug fix**, relevant tests have been included.
- [ ] Because this PR includes a **new feature**, the change was previously discussed on an Issue or with someone from the team.
- [x] I didn't do anything of this.

---

### CODE REVIEW

**Comment by alcuadrado** [comment]
Thanks for submitting this PR!

Can you sign the CLA so we can merge this? Thanks!

**Comment by samlaf** [comment]
image
Not sure how to do that... the cla-assistant seems to not be working properly.

**Comment by samlaf** [comment]
Also are there alternatives to CLA assistant?
I don't like that I have to give them write access to my public AND secret gists... see https://github.com/cla-assistant/cla-assistant/issues/65

**Comment by alcuadrado** [comment]
I didn't know it wasn't working. I'll see what I can do. Will get back to you soon.

**Pull request merged**
