### PR TITLE
Update plugins.ts

### PR DESCRIPTION
**Pull request by TovarishFin**
When trying to use yul, I found that the plugin no longer worked. I did a fairly large rewrite and made a few improvements on top of it. Please consider using my fork instead of the original.

- [ ] Because this PR includes a **bug fix**, relevant tests have been included.
- [ ] Because this PR includes a **new feature**, the change was previously discussed on an Issue or with someone from the team.
- [x] I didn't do anything of this.

---

### CODE REVIEW

**Comment by fvictorio** [comment]
Hey @TovarishFin, it seems like the upstream project merged a PR from you, do you still want to add your fork to the list?

**Comment by TovarishFin** [comment]
He wanted to chat with me on telegram but never wrote me back... not sure what is going on with him. regardless this is a bit more than i signed up for. Do whatever you think is the best course. 

I would submit one piece of info favoring my fork though. His version never had an NPM package. Mine does. And it matches my name. If the plugin uses his, it will still end up using my NPM package since he just pulled my changes (including the docs). 

Anyways do whatever you want. It doesn't matter much to me either way :)

Either way I will continue to update and use my own fork since I am using it daily.

**Comment by fvictorio** [comment]
In that case I don't mind adding it as a different plugin and saying in the description that it's a more up-to-date fork. We can consider replacing it entirely in the future. I would understand if you don't want to invest more time in this PR though.

**Comment by TovarishFin** [comment]
Alright so I updated it to leave the original and just add my fork. Hopefully this works for you.

**Comment by fvictorio** [comment]
Thank you!

**Pull request merged**
