### PR TITLE
test: add tests for calculating block timestamp

### PR DESCRIPTION
**Pull request by Wodann**

### CODE REVIEW

**Review by fvictorio — APPROVED** [review]
I focused mainly on the tests, which LGTM.

**Comment by Wodann** [comment]
> I focused mainly on the tests, which LGTM.

Thanks. I'll wait for Agost's approval for the Rust code then.

**Review by agostbiro — APPROVED** [review]
Thanks, LGTM!

**Comment by fvictorio** [comment]
Transferred to https://github.com/NomicFoundation/edr/pull/395

**Pull request closed without merging**
