### PR TITLE
feat: add `eth_signTypedData_v4` support

### PR DESCRIPTION
**Pull request by agostbiro**
Add `eth_signTypedData_v4` support and enable relevant Hardhat integration tests.

### CODE REVIEW

**Review by Wodann — APPROVED** [review]
The code looks good to me; nice and simple. However, there are failing tests due to panics in EDR. Could you solve those before merging please?

**Comment by agostbiro** [comment]
I dug into this and the transaction failures are due to `maxFeePerBlobGas` is missing from a type `0x3` transaction. It's either a [Geth problem](https://github.com/ethereum/go-ethereum/issues/28841) or an Alchemy problem (reached out via Discord support), so I think this is safe to merge.

**Comment by Wodann** [comment]
> I dug into this and the transaction failures are due to `maxFeePerBlobGas` is missing from a type `0x3` transaction. It's either a [Geth problem](https://github.com/ethereum/go-ethereum/issues/28841) or an Alchemy problem (reached out via Discord support), so I think this is safe to merge.

To avoid panics in the future, is there a way we can bubble up the error, such that the background thread doesn't crash?

**Comment by agostbiro** [comment]
> > I dug into this and the transaction failures are due to `maxFeePerBlobGas` is missing from a type `0x3` transaction. It's either a [Geth problem](https://github.com/ethereum/go-ethereum/issues/28841) or an Alchemy problem (reached out via Discord support), so I think this is safe to merge.
> 
> To avoid panics in the future, is there a way we can bubble up the error, such that the background thread doesn't crash?

Done here: https://github.com/NomicFoundation/hardhat/pull/4775

**Pull request merged**
