### PR TITLE
Add support for `--chainid` argument in `node` command 

### PR DESCRIPTION
**Pull request by prajnastra**
- [ ] Because this PR includes a **new feature**, the change was previously discussed on an Issue or with someone from the team. (Issues #2305)

---

This PR adds support for `--chainid` argument in `npx hardhat node` command.

### CODE REVIEW

**Comment by alcuadrado** [comment]
Thanks, @webdevabhijit!

@fvictorio will review this after we get our next release out.

**Comment by webdevabhijit** [comment]
@alcuadrado Sure.

**Comment by luncht1me** [comment]
Still relevant.

**Comment by fvictorio** [comment]
Hey @ethabhijit, thanks for the PR and sorry for taking so long to respond.

I don't think this implementation works, unless I'm missing something. The reason is that it relies on using `hardhat_reset` with the new `chainId`, but I'm pretty sure that `hardhat_reset` doesn't support that. So I would say that this feature is blocked by https://github.com/NomicFoundation/hardhat/issues/1697

In the meantime, for people landing here, a workaround for this missing feature is to use an environment variable. You should set something like this in your hardhat config:

```js
networks: {
  hardhat: {
    chainId: Number(process.env.HARDHAT_CHAIN_ID) ?? 31337
  },
},
```

And then `HARDHAT_CHAIN_ID=123 npx hardhat node` should use 123 as a chain id.

**Pull request closed without merging**
