### PR TITLE
Bump `hardhat-toolbox` dev & peer dependencies

### PR DESCRIPTION
**Pull request by pcaversaccio**
This will fix, amongst others, current errors coming from the recent `@types/mocha` upgrade to version `10.0.0`.

Example error/warning:

```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @nomicfoundation/hardhat-toolbox@2.0.0
npm ERR! Found: @types/mocha@10.0.0
npm ERR! node_modules/@types/mocha
npm ERR!   dev @types/mocha@"^10.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @types/mocha@"^[9](https://github.com/pcaversaccio/create2deployer/actions/runs/3158062080/jobs/5139668583#step:5:10).1.0" from @nomicfoundation/hardhat-toolbox@2.0.0
npm ERR! node_modules/@nomicfoundation/hardhat-toolbox
npm ERR!   dev @nomicfoundation/hardhat-toolbox@"^2.0.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @types/mocha@9.1.1
npm ERR! node_modules/@types/mocha
npm ERR!   peer @types/mocha@"^9.1.0" from @nomicfoundation/hardhat-toolbox@2.0.0
npm ERR!   node_modules/@nomicfoundation/hardhat-toolbox
npm ERR!     dev @nomicfoundation/hardhat-toolbox@"^2.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/runner/.npm/eresolve-report.txt for a full report.
```

### CODE REVIEW

**Comment by pcaversaccio** [comment]
hmm not sure why linting is failing tbh...

**Comment by fvictorio** [comment]
Hey @pcaversaccio, thanks for this. I think the problem is that, when we upgraded mocha to v10, the `@types` for that version were not published yet. IIRC there weren't any API changes between v9 and v10, or they were very minimal, so we just used the v9 types.

I opened https://github.com/NomicFoundation/hardhat/pull/3233, which only updates those, and it updates the version in Hardhat core too. I'm going to close this in favor of that one, but please let me know if there's some change you'd like to see there. Notice that the other things you are upgrading are either dev dependencies (that we upgrade in the whole monorepo at once, and we have a check for that, which is likely why the lint check is failing) or they are not strictly necessary because they are already included in the `^` range.

**Comment by fvictorio** [comment]
Oh, also, it would be very useful if you could tell me why you ran into this issue. Do you need the latest `@types/mocha` for some reason? If so, can you explain why? Asking to prioritize this change, because I think it _technically_ is a major change, since we are changing a major version of a peer dependency.

**Comment by pcaversaccio** [comment]
@fvictorio actually there is no specific reason - I maintain a couple of open-source repos that contain Hardhat dependencies and I try to keep the deps up-to-date. For that reason, I check bi-weekly for new releases and test for compatibility or what I need to upgrade. One repository you hopefully will like is my [Hardhat project template](https://github.com/pcaversaccio/hardhat-project-template-ts) :).

**Comment by fvictorio** [comment]
> One repository you hopefully will like is my [Hardhat project template](https://github.com/pcaversaccio/hardhat-project-template-ts) :).

That looks super good! We are planning to make some kind of curated list of templates out there, I'll make sure we include this one :smile:

**Comment by pcaversaccio** [comment]
thanks very much @fvictorio!

**Pull request closed without merging**
