### PR TITLE
perf(fs): use realpathSync native for >15%. improvement [HH-446]

### PR DESCRIPTION
**Pull request by sambacha**
- [ ] Because this PR includes a **bug fix**, relevant tests have been included.
- [ ] Because this PR includes a **new feature**, the change was previously discussed on an Issue or with someone from the team.
- [x] I didn't do anything of this.

---

# Performance: Faster Load Time with `realPathSync.native`

TypeScript now leverages a **system-native** implementation of the Node.js `realPathSync` function on all operating systems.

Previously this function was only used on Linux, but in TypeScript 4.5 it has been adopted to operating systems that are typically case-insensitive, like Windows and MacOS. On certain codebases, this change sped up project loading by 5-13% (depending on the host operating system).

## Reference material

For more information, see [the original change here](https://github.com/microsoft/TypeScript/pull/44966), along with [the 4.5-specific changes here](https://github.com/microsoft/TypeScript/pull/44966).

[ref: https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/#real-path-sync-native](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/#real-path-sync-native)

## Discussion

This is a rough cut, would like some feedback if you guys are interested in these possible changes (it does enforce at least typescript 4.5, and you are using ~ for semver of typescript)

Additionally, changing how `tmpDir` is managed with instead `mkdtmp` the nodejs utility is something I observed as a possible easy change that would yield very slight gain (potentially). Another would be instead of downloading repeatedly solidity compilers offer a global config option (I am sure users would do this) + offer a more compressed binary for solc native (quicker downloads). etc etc.  

### Notes

Originally scoped out files
<pre>
packages/hardhat-core/test/helpers/project.ts
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test.ts
packages/hardhat-core/test/internal/hardhat-network/stack-traces/compilation.ts
packages/hardhat-core/test/internal/util/download.ts
packages/hardhat-core/test/internal/util/packageInfo.ts
packages/hardhat-core/test/internal/core/typescript-support.ts
packages/hardhat-core/test/internal/solidity/helpers.ts
packages/hardhat-core/test/internal/solidity/dependencyGraph.ts
packages/hardhat-core/src/builtin-tasks/utils/solidity-files-cache.ts
</pre>

### Reference` fs.([1], :[2])`
```js
fs.link(srcpath, dstpath, callback);             // Asynchronous link. No arguments other than a possible exception are given to the completion callback.
fs.linkSync(srcpath, dstpath);                   // Synchronous link.
fs.symlink(srcpath, dstpath, [type], callback);  // Asynchronous symlink. No arguments other than a possible exception are given to the completion callback. The type argument can be set to 'dir', 'file', or 'junction' (default is 'file') and is only available on Windows (ignored on other platforms)
fs.symlinkSync(srcpath, dstpath, [type]);        // Synchronous symlink.
fs.readlink(path, callback);                     // Asynchronous readlink. The callback gets two arguments (err, linkString).
fs.readlinkSync(path);                           // Synchronous readlink. Returns the symbolic link's string value.
fs.unlink(path, callback);                       // Asynchronous unlink. No arguments other than a possible exception are given to the completion callback.
fs.unlinkSync(path);                             // Synchronous unlink.

fs.realpath(path, [cache], callback);     // Asynchronous realpath. The callback gets two arguments (err, resolvedPath).
fs.realpathSync(path, [cache]);           // Synchronous realpath. Returns the resolved path.
```

### CODE REVIEW

**Comment by sambacha** [comment]
> [CLA assistant check](https://cla-assistant.io/NomicFoundation/hardhat?pullRequest=2522) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/NomicFoundation/hardhat?pullRequest=2522) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/NomicFoundation/hardhat?pullRequest=2522) it.

This CLA covers any potential contribution to Nomic that does not necessarily include hardhat?

**Comment by fvictorio** [comment]
This looks really interesting, thanks a lot @sambacha, we'll take a look as soon as we can.

> This CLA covers any potential contribution to Nomic that does not necessarily include hardhat?

I'm not really sure. Tagging @alcuadrado that knows this stuff.

**Comment by alcuadrado** [comment]
I've just removed the CLA bot. Now that we relicensed everything to MIT it's no longer necessary.

**Comment by sambacha** [comment]
Thanks guys, also would you be interested in leveraging Turborepo? I have another branch with that setup to build the entire repository. It is much faster for building the monorepo, should check it out imho

**Comment by sambacha** [comment]
Also btw thanks for addressing my CLA question, makes contributing much easier

**Comment by fvictorio** [comment]
> Thanks guys, also would you be interested in leveraging Turborepo? I have another branch with that setup to build the entire repository. It is much faster for building the monorepo, should check it out imho

That's really interesting, we'll take a look. Thanks for the tip!

**Comment by alcuadrado** [comment]
There's something weird going on with github actions here. I think this PR was created when it was down

**Comment by alcuadrado** [comment]
Can you add an empty commit or give me access to push to your branch, @sambacha? Thanks!

**Comment by alcuadrado** [comment]
I've been reading more about this, and it's a great idea! `realpathSync.native` returns the path with the casing as it is on disk, so we don't need to use `true-case-path` anymore.

**Comment by alcuadrado** [comment]
Replaced by #3053. Thanks again, @sambacha

**Pull request closed without merging**
