### PR TITLE
add aurora to hardhat-etherscan

### PR DESCRIPTION
**Pull request by baboobhaiya**
- [ ] Because this PR includes a **bug fix**, relevant tests have been included.
- [ ] Because this PR includes a **new feature**, the change was previously discussed on an Issue or with someone from the team.
- [x] I didn't do anything of this.

---

Adds aurorascan details for verifying contracts on aurora chain

JSPN-RPC: https://mainnet.aurora.dev/
Funds deposited: https://aurorascan.dev/address/0x4444c3F7D7d3153Dc0773C31ae10cf9B5495d4Bb

### CODE REVIEW

**Comment by baboobhaiya** [comment]
have followed the steps @alcuadrado

**Comment by alcuadrado** [comment]
Can you also add support for the testnet, like https://github.com/nomiclabs/hardhat/pull/2371 does?

**Comment by baboobhaiya** [comment]
its done

**Comment by alcuadrado** [comment]
Thanks! Can you send some testnet eth? That's all that's left for us to test it.

**Comment by baboobhaiya** [comment]
sorry for the delay you should have the funds now in testnet as well

**Pull request merged**
