### PR TITLE
Improve/flatten task smarter 1499

### PR DESCRIPTION
**Pull request by dai-dao**
- [X] Because this PR includes a **new feature**, it uses the `development` branch as its base branch.
- [X] Because this PR includes a **new feature**, the change was previously discussed on an Issue or with someone from the team.

Make flatten task smarter according to [this document](https://www.notion.so/New-flatten-task-spec-44f2282a0f9c4386bfd2d6f254c96e1c) following this [issue](https://github.com/nomiclabs/hardhat/issues/1499)

### CODE REVIEW

**Comment by dai-dao** [comment]
Thanks for reviewing :)

**Comment by alcuadrado** [comment]
@dai-dao, are you willing to finish this pr, or should we finish it?

**Comment by dai-dao** [comment]
Hello sorry I had an interview coming up so was busy preparing for that, but yea i'm back now and will get to finish this PR

**Comment by dai-dao** [comment]
> Just a quick question without having looked at the code: how does this behave for other pragma directives? Maybe we should have some generic fallback behavior

I'm just handling the case with abicoder and experimental for now, since these two can have different versions v1 and v2. I'm not handling the case though with different Solidity versions since it's not mentioned in the notion doc, but perhaps i should get the latest versions if multiple are present?

**Comment by alcuadrado** [comment]
Hey @dai-dao, sorry we accidentally closed this PR

**Comment by partylikeits1983** [comment]
quick and dirty way with python: 

`import os

bad_words = ['SPDX-License-Identifier', 'pragma']

with open('/home/ubuntu/Desktop/defiBank/contracts/flatten.sol') as oldfile, open('/home/ubuntu/Desktop/defiBank/contracts/flatten1.sol', 'w') as newfile:
    for line in oldfile:
        if not any(bad_word in line for bad_word in bad_words):
            newfile.write(line)
            
filename = "/home/ubuntu/Desktop/defiBank/contracts/flatten1.sol"

string = "// SPDX-License-Identifier: MIT \n pragma solidity ^0.8.0; \n"
            
def insert(originalfile,string):
    with open(originalfile,'r') as f:
        with open('newfile.txt','w') as f2: 
            f2.write(string)
            f2.write(f.read())
    os.rename('newfile.txt',originalfile)
    
insert(filename,string)`

**Comment by Jerrywang959** [comment]
When can we use this new feature :sob:

**Comment by kalloc** [comment]
Hi, any news?

**Comment by fvictorio** [comment]
This was implemented in https://github.com/NomicFoundation/hardhat/pull/4173 and released in [Hardhat v2.17.1](https://github.com/NomicFoundation/hardhat/releases/tag/hardhat%402.17.1).

**Pull request closed without merging**
