### PR TITLE
Glob package bug fix for Issue 2712

### PR DESCRIPTION
**Pull request by tylerK1294**
https://github.com/NomicFoundation/hardhat/issues/2712

- [ ] Because this PR includes a **bug fix**, relevant tests have been included.
- [ ] Because this PR includes a **new feature**, the change was previously discussed on an Issue or with someone from the team.
- [x] I didn't do anything of this.

---

https://github.com/NomicFoundation/hardhat/issues/2712#issuecomment-1126720047
I fixed the version of glob package because it worked well in 7.2.0 version.

### CODE REVIEW

**Comment by fvictorio** [comment]
Hey @tylerK1294, I published a version with this change under the `dev` tag. Can you please try it out and let me know if it works for you?

You can install it with `npm i hardhat@dev`. Thank you!

**Comment by tylerK1294** [comment]
> Hey @tylerK1294, I published a version with this change under the `dev` tag. Can you please try it out and let me know if it works for you?
> 
> You can install it with `npm i hardhat@dev`. Thank you!

I checked that it works well in Windows environment. 
The bug was fixed after installing the dev version. 
Thanks!

**Comment by fvictorio** [comment]
Thank you! We'll release a proper new version soon with this change then.

**Comment by fvictorio** [comment]
Hey @tylerK1294, we just released [`hardhat@2.9.6`](https://github.com/NomicFoundation/hardhat/releases/tag/hardhat%402.9.6), which fixes this. I did this change in a separate PR so I could also update our `yarn.lock`. Thanks a lot!

**Pull request closed without merging**
