### PR TITLE
Docs: Update to lock chai at version 4

### PR DESCRIPTION
**Pull request by lilpolymath**
- [ ] Because this PR includes a **bug fix**, relevant tests have been included.
- [ ] Because this PR includes a **new feature**, the change was previously discussed on an Issue or with someone from the team.
- [x] I didn't do anything of this.

---

Locks `chai` to version 4. [See conversation]( https://github.com/NomicFoundation/hardhat/issues/4733)

### CODE REVIEW

**Comment by fvictorio** [comment]
This looks good, thanks @lilpolymath. But is there a reason why you removed the `@5` from ethers? Those instructions also use `@nomiclabs/hardhat-ethers` (the previous version of the ethers plugin) which doesn't work with ethers v6.

**Comment by lilpolymath** [comment]
@fvictorio that was an oversight. I noticed that some installations for `ethers` were not locked to version 5 and I erroneously thought I had introduced that change. Fixing in a minute.

**Comment by lilpolymath** [comment]
@fvictorio fixed.

**Review by fvictorio — APPROVED** [review]

**Comment by fvictorio** [comment]
Hey, sorry for not merging this sooner, this looks good! You missed a couple of files but I already updated them. Thanks!

**Pull request merged**
