### PR TITLE
Check if contract is already verified before attempting verification

### PR DESCRIPTION
**Pull request by OptimusOpus**
- [x ] Because this PR includes a **new feature**, the change was previously discussed on an Issue or with someone from the team.

This PR addresses the issue discussed [here](https://github.com/NomicFoundation/hardhat/issues/2287)

### CODE REVIEW

**Comment by jakerockland** [comment]
Woo–thank you for doing this @OptimusOpus – cc @ryley-o

**Comment by alcuadrado** [comment]
I simplified the implementation and moved the check so that other validations (like compiler version vs your config) don't even run if the contract is already verified.

Sorry I mostly reimplemented it, but this plugin has a ton of technical debt, so everything is risky.

**Comment by alcuadrado** [comment]
Oh, do you mind allowing me to push to your branch, @OptimusOpus? thanks!

**Comment by OptimusOpus** [comment]
> Oh, do you mind allowing me to push to your branch, @OptimusOpus? thanks!

Not at all, thanks @alcuadrado

**Comment by alcuadrado** [comment]
It doesn't seem to work. I replaced this PR with https://github.com/NomicFoundation/hardhat/pull/3675

**Pull request closed without merging**
