### PR TITLE
hardhat-etherscan: Add arbitrum testnet support.

### PR DESCRIPTION
**Pull request by kr1p70n1c**
- [ ] Because this PR includes a **documentation change**, its branch was created from the `website` branch, and this PR uses the `website` branch as its base branch.
- [ ] Because this PR includes a **bug fix**, relevant tests have been included.
- [ ] Because this PR includes a **new feature**, the change was previously discussed on an Issue or with someone from the team.
- [x] I didn't do anything of this.

---

Added support for `Arbitrum Testnet`.

Tested this with `npm link` from a blockchain project and that I could successfully verify contracts on this testnet.

### CODE REVIEW

**Comment by fvictorio** [comment]
Hey @kr1p70n1c, thanks a lot for this. Can you tell me how I can double-check that this works? Is there some faucet for the Arbitrum testnet or do I need to bridge test eth from some testnet? Thanks!

**Comment by kr1p70n1c** [comment]
Hi @fvictorio,

If you have test ETH on the Rinkeby network, you can bridge over to Arbitrum testnet here:

https://bridge.arbitrum.io/

Alternatively I can also send you test ETH for the Arbitrum testnet, can just provide me with an address.

kr1p70n1c

**Comment by kr1p70n1c** [comment]
@fvictorio thanks for the review!

**Comment by kr1p70n1c** [comment]
> @fvictorio thanks for the review!
> 
> Do you perhaps know (roughly) when the `@nomiclabs/hardhat-etherscan` package's version will get bumped?

@fvictorio apologies for bumping you on this again, but do you have any idea on the above ⬆️  ?

**Comment by fvictorio** [comment]
Hey, sorry. I think we might be able to do a release today, I'll comment here if/when we do.

**Comment by fvictorio** [comment]
@kr1p70n1c we just published `@nomiclabs/hardhat-etherscan@2.1.7`, which includes this change.

**Comment by kr1p70n1c** [comment]
> @kr1p70n1c we just published `@nomiclabs/hardhat-etherscan@2.1.7`, which includes this change.

@fvictorio great! thanks so much, appreciated.

**Pull request merged**
