### PR TITLE
feat: add Optimism provider

### PR DESCRIPTION
**Pull request by Wodann**
A draft PR for adding Optimism support in EDR using the `@ignored/edr-optimism` package, intended for the alpha.

### CODE REVIEW

**Comment by schaable** [comment]
@Wodann I've [merged](https://github.com/NomicFoundation/hardhat/pull/5811/commits/79de6904dbafb8202111acdf3b81bddadf66d0ef) this PR into the `feat/edr-provider` branch, so we can close this. There are a couple of enums, like `StackTraceEntryType` and `MineOrdering`, that still need to be converted to constants. I've casted the values for now to get things working, but we should revisit this in the future to clean it up.

**Comment by Wodann** [comment]
> @Wodann I've [merged](https://github.com/NomicFoundation/hardhat/pull/5811/commits/79de6904dbafb8202111acdf3b81bddadf66d0ef) this PR into the `feat/edr-provider` branch, so we can close this. There are a couple of enums, like `StackTraceEntryType` and `MineOrdering`, that still need to be converted to constants. I've casted the values for now to get things working, but we should revisit this in the future to clean it up.

Are enums prohibited?

Could you provide an example of what you'd like to be generated instead of an enum?

**Comment by Wodann** [comment]
> The issue is that we have [`isolatedModules`](https://www.typescriptlang.org/tsconfig/#isolatedModules) set to true to ensure compatibility with single-file transpilation tools like `tsx`. With `isolatedModules`, `const enum`s can’t be inlined, since this setting assumes each file compiles independently rather than together.
> 
> Instead of using enums, it would be better to generate constants, similar to what was done for `SpecId`.

Thanks for explaining! I'll add a task to do that and add you as a reviewer.

**Comment by Wodann** [comment]
[Issue added](https://github.com/NomicFoundation/edr/issues/721)

**Pull request closed without merging**
