### PR TITLE
Add hardhat-deal amongst hardhat plugins

### PR DESCRIPTION
**Pull request by Rubilmax**
- [ ] Because this PR includes a **bug fix**, relevant tests have been included.
- [ ] Because this PR includes a **new feature**, the change was previously discussed on an Issue or with someone from the team.
- [x] I didn't do anything of this.

---

I'd like to get my hardhat plugin listed on the Hardhat plugins page

### CODE REVIEW

**Comment by Karuzzzo** [comment]
https://github.com/Karuzzzo/deals
Lol, looks like we got the same idea and same naming wtf

**Comment by Rubilmax** [comment]
> https://github.com/Karuzzzo/deals Lol, looks like we got the same idea and same naming wtf Although I only made task for hardhat, not a function. Maybe we can merge it in one package or something?)

I'd be happy to merge a PR of yours adding the feature as a task! Let's continue this discussion [here](https://github.com/Rubilmax/hardhat-deal/issues/3)

**Comment by fvictorio** [comment]
Should we close this PR?

**Comment by Rubilmax** [comment]
> Should we close this PR?

I don't understand: why would you close this PR please? I'm trying to get my hardhat plugin listed among other hardhat plugins.

**Comment by Karuzzzo** [comment]
This plugin differs from mine, and does its job much better. 
Should be merged 100%

**Comment by fvictorio** [comment]
Ugh, sorry @Rubilmax, I read your conversation backwards and I thought you were agreeing to merge your PR into @Karuzzzo's. Of course we can merge this :slightly_smiling_face:

**Pull request merged**
