### PR TITLE
Fix load fixture issue when reverting to future state

### PR DESCRIPTION
**Pull request by skosito**
- [x] Because this PR includes a **bug fix**, relevant tests have been included.
- [ ] Because this PR includes a **new feature**, the change was previously discussed on an Issue or with someone from the team.
- [ ] I didn't do anything of this.

---

Please check this issue https://github.com/NomicFoundation/hardhat/issues/3249 for more details and discussion.

The way that loadFixture is working now is that allows situations like this:

```
Load fixture 1
...
Load fixture n - 1
Load fixture n
```

Up until this point every loadFixture takes a snapshot and store it in snapshots array. If loadFixture is called for any `n-i` it will work because it reverts the state to previous state. However, it also allows this, which fails because it tries to revert from previous to future state:

```
Load fixture 1
...
Load fixture n 
Load fixture n - i
Load fixture n -> fails with invalid snapshot error
```

My proposal is to remove all snapshots that have snapshot id bigger than snapshot being restored. This way it will ensure that every time loadFixture is called for future state snapshot is simple re-taken again.
Running tests in hardhat-network-helpers package failed only one test, describing exactly this issue, so i modified it.
I tested this a bit in project I am working on and it fixed the issue.

### CODE REVIEW

**Comment by fvictorio** [comment]
Thanks for sending this @skosito! I will try to review this as soon as I have some time.

**Comment by skosito** [comment]
> Thanks for sending this @skosito! I will try to review this as soon as I have some time.

Hey @fvictorio did you have a chance to take a look?

**Comment by fvictorio** [comment]
Hey, sorry, not yet. I'll try to do it this week so we can include this in the next release.

**Comment by Aminadav** [comment]
I confirm that I had the same issue as mentioned, and when I use the patch it fixed it for me.

**Review by Aminadav — APPROVED** [review]
I confirm that I had the same issue as mentioned, and when I use the patch it fixed it for me.

**Comment by skosito** [comment]
@fvictorio There were some linter errors in workflows, i fixed them in new commit

**Comment by fvictorio** [comment]
> Looks like now the test is missing to cover scenario where snapshot is invalid for other reasons. Do you have some suggestions how to add that?

Not really, hopefully that simply won't happen? Well, unless someone manually reverts a snapshot with a snapshot id they didn't obtain... but that's too far-fetched. I'm ok with not testing it.

There was a very fun bug related to snapshot ids being strings that were being compared with `<=`. I fixed that. You can take a look at the new test to see how that could cause an error. It was unlikely to happen, but still.

That aside, this is a great PR, thanks for sending it!

**Comment by skosito** [comment]
> > Looks like now the test is missing to cover scenario where snapshot is invalid for other reasons. Do you have some suggestions how to add that?
> 
> Not really, hopefully that simply won't happen? Well, unless someone manually reverts a snapshot with a snapshot id they didn't obtain... but that's too far-fetched. I'm ok with not testing it.
> 
> There was a very fun bug related to snapshot ids being strings that were being compared with `<=`. I fixed that. You can take a look at the new test to see how that could cause an error. It was unlikely to happen, but still.
> 
> That aside, this is a great PR, thanks for sending it!

@fvictorio thanks for info and adding that test, and thanks for checking this!

**Comment by fvictorio** [comment]
Thank you!

**Pull request merged**
