### PR TITLE
Fork network name

### PR DESCRIPTION
**Pull request by wighawag**
This PR allow user to specify a network to fork from, instead of an url.
It will use the url set in the network config for thar network name

This is a very useful feature for plugin like `hardhat-deploy` because that way, the plugins can know which network it was forked from and bring the usual context for that network (named accounts, deployments, etc...)

This fixes https://github.com/nomiclabs/hardhat/issues/1164

### CODE REVIEW

**Comment by alcuadrado** [comment]
We've been discussing this further with @fvictorio.

We had these alternative ideas that may be useful to fix the problem you described to me on tg.

1. Make the `HardhatArguments`, including the network name, and the `taskName` available in the config.
2. Make the `HardhatArguments` extensible, so that you could define, for example, `--fork-network`.

Note that they contradict each other and only one of them can be implemented, and that in both cases you would require an API to hook into the provider initialization process.

**Comment by paulrberg** [comment]
This is not strictly related to the use case mentioned by @wighawag, but:

> Make the HardhatArguments, including the network name, and the taskName available in the config.

This will implicitly solve https://github.com/nomiclabs/hardhat/issues/1795, since I could check at the top-level scope for the network chosen by the user, choose either the `ETHERSCAN_API_KEY` or the `POLYGONSCAN_API_KEY` env var and pass it to the `apiKey` field.

**Comment by sebastianst** [comment]
Any update on this?

**Comment by alcuadrado** [comment]
Closing to clean up the repo. We still like this idea, and may implement it.

**Pull request closed without merging**
