### PR TITLE
Create env before args are parsed

### PR DESCRIPTION
**Pull request by theethernaut**
Solves https://github.com/NomicFoundation/hardhat/issues/4950

### CODE REVIEW

**Comment by alcuadrado** [comment]
Hey @theethernaut, do you mind rebasing this on top of `main`?

**Comment by alcuadrado** [comment]
This LGTM, but I think we should run the CI after the rebase before merging.

**Comment by theethernaut** [comment]
Hey @alcuadrado 👋 

Rebase done :)

**Comment by alcuadrado** [comment]
Merged this despite 3 checks failing, as those were EDR-related, and not affected by this PR. The reason they failed is independent from this PR, and related to our setup instead.

**Comment by theethernaut** [comment]
Thank you!

**Pull request merged**
