### PR TITLE
Add Troubleshooting documentation for mainnet forking

### PR DESCRIPTION
**Pull request by thatguyintech**
- [x] Because this PR includes a **documentation change**, its branch was created from the `website` branch, and this PR uses the `website` branch as its base branch.

Multiple users have been confused after seeing this issue:
https://github.com/nomiclabs/hardhat/issues/1507

Adding this note to the troubleshooting section will help clarify
ways to solve this problem.

### CODE REVIEW

**Comment by fvictorio** [comment]
Thanks a lot @thatguyintech, this seems really useful.

> One way to fix this is to try connecting to a different internet network.

Can you clarify what you mean by that? Using a different VPN, a different IPS, or something else?

**Comment by thatguyintech** [comment]
> Using a different VPN, a different ISP, or something else?

Yeah I think all of these may help, it's not clear to me which one seems to be the more common culprit. I'll add that into the docs to be more specific about things people can try!

**Comment by thatguyintech** [comment]
@fvictorio updated! lmk how that looks

**Comment by thatguyintech** [comment]
@fvictorio is this copy ok?

**Comment by thatguyintech** [comment]
@feuGeneA any thoughts?

**Comment by alcuadrado** [comment]
Re-reading this PR I got the idea/impression that we are throwing a misleading error when HH109 is thrown from the forking functionality's JSON-RPC client. I think what we should do instead is catching it [here](https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-core/src/internal/hardhat-network/jsonrpc/client.ts#L319) and throwing something with more context.

**Comment by fvictorio** [comment]
Hey @thatguyintech, sorry for the auto-close and for not merging this PR.

We recently changed the structure of our site significantly, so if you want to open a new PR with this change, we'll try to get it merged as soon as we can.

**Comment by thatguyintech** [comment]
Awesome, I'll take a look

**Pull request closed without merging**
