### PR TITLE
Hardhat storage dumper

### PR DESCRIPTION
**Pull request by Karuzzzo**
This pull request introduces task allowing users to dump a contract's storage layout into stdout. It uses eth_getStorageAt calls 🔍. 
It is compatible with any node provider, making it easy to inspect and analyze the storage structure of any Ethereum smart contract on various networks. 

Changes:

Update README with installation instructions and usage examples
Support for verbose output, prints whole storage slots from-to
Can detect some types of variables, and I'm really working into mappings. It's possible to read some of the data from them.
Please review and provide feedback. If everything looks good, feel free to merge the changes into the main branch.

Thank you! 🚀

### CODE REVIEW

**Comment by Karuzzzo** [comment]
And yes, naming is kinda weird. Shouldve named it like hardhat-storage-layout or something. 
But whatever..

**Comment by fvictorio** [comment]
Hey @Karuzzzo, can you please run prettier in the modified file? I tried to do it, but I can't push to your branch for some reason.

**Comment by fvictorio** [comment]
The CI is still failing :sweat_smile: 

You should be able to fix this by running `yarn lint:fix` at the root of the repository.

**Comment by Karuzzzo** [comment]
I'm really confused lol
```yarn lint:fix``` shows no errors
```git diff``` shows no changes
Lint fails
...
???

**Comment by fvictorio** [comment]
Oops, my bad. You are right, that script doesn't include the `plugins.ts` file. I fixed this in a [new PR](https://github.com/NomicFoundation/hardhat/pull/3797), I'm going to close this one in favor of that.

**Comment by Karuzzzo** [comment]
yaaaaay

**Pull request closed without merging**
