### PR TITLE
Show selector in "unrecognized custom error" msg

### LINKED ISSUE #2948: Blind "reverted with an unrecognized custom error"
Please add hex representation of "unrecognized custom error". Sometimes revert comes from external smart contract, we have no source code. Especially when we fork mainnet.

### PR DESCRIPTION
**Pull request by feuGeneA**
Fixes #2948

### CODE REVIEW

**Comment by fvictorio** [comment]
Ok, this one was hard to test. I wonder how users run into this, because it's not easy to trigger.

Anyway, this is what I did. I deployed and called `f` on this contract:

```solidity
contract Foo {
  function f() public {
    assembly {
      mstore(0x80, 0x1234567800000000000000000000000000000000000000000000000000000000)
      revert(0x80, 4)
    }
  }
}
```

And got this error message:

```
Error: VM Exception while processing transaction: reverted with an unrecognized custom error with selector 12345678
```

**Review by fvictorio — APPROVED** [review]

**Comment by k06a** [comment]
@fvictorio it's easy to reproduce if you have tests with mainnet fork.

**Comment by fvictorio** [comment]
@k06a I will make a release that includes this change tomorrow :slightly_smiling_face:

**Comment by fvictorio** [comment]
@k06a we just released [Hardhat v2.20.2](https://github.com/NomicFoundation/hardhat/releases/tag/hardhat%402.10.2) which includes this change :tada:

**Comment by kevincheng96** [comment]
This is a great feature! But somehow, I'm not able to hit the specific codepath in `error-inferrer.ts` on my end. Instead, the error I'm getting is from [`solidity-error.ts`](https://github.com/NomicFoundation/hardhat/blob/5a9927dd2ecbb6bbe60b35972c5969981cc080f3/packages/hardhat-core/src/internal/hardhat-network/stack-traces/solidity-errors.ts#L274) instead, which does not include the custom error selector. Curious why there are two error paths and what's the difference between them. Also, should we also add the custom error selector to the error in `solidity-error.ts`?

**Comment by fvictorio** [comment]
@kevincheng96 do you have reproduction steps? If so, can you please open a new issue about this?

**Comment by kevincheng96** [comment]
> @kevincheng96 do you have reproduction steps? If so, can you please open a new issue about this?

@fvictorio sorry for the delay! Sure, I just opened a [new issue](https://github.com/NomicFoundation/hardhat/issues/3237) for this and it links out to some reproduction steps.

**Pull request merged**
