### PR TITLE
HttpProxy envs while interacting with networks

### PR DESCRIPTION
**Pull request by furkilic**
- [X] Because this PR includes a **new feature**, it uses the `development` branch as its base branch.

---

Being behind a Corporate HttpProxy, I'd like to add the feature to deploy/interact with networks by using standard environment variables : HTTPS_PROXY or HTTP_PROXY .

Linked to #1978

### CODE REVIEW

**Comment by fvictorio** [comment]
Hey @furkilic, could you rebase this to use the `master` branch instead?

**Comment by furkilic** [comment]
Hi @fvictorio
Tried to do it though the UI first but failed miserably
The rebase should be ok now

**Comment by suil** [comment]
any updates on this?

**Review by suil — APPROVED** [review]

**Comment by Vallsurf** [comment]
Anything blocking from this being merged?  Would be a huge help.

**Pull request closed without merging**
