### PR TITLE
Use proper async/await syntax in sample code

### PR DESCRIPTION
**Pull request by delaaxe**
- [ ] Because this PR includes a **bug fix**, relevant tests have been included.
- [ ] Because this PR includes a **new feature**, the change was previously discussed on an Issue or with someone from the team.
- [x] I didn't do anything of this.

---

Avoid using deprecate Promise based syntax

### CODE REVIEW

**Comment by alcuadrado** [comment]
Hey! this pr caught my attention. Deprecated? Do you have more info about it?

**Comment by delaaxe** [comment]
> Hey! this pr caught my attention. Deprecated? Do you have more info about it?

Sorry didn't get notified for some reason 

It's just regular old async/await, where rejections are meant to be dealt in try/catch blocks, instead of the old promise based `.then()`/`.catch()`.

The surrounding IIFE is to enable async/await at module level

**Comment by fvictorio** [comment]
@delaaxe "deprecated" usually means "it will be removed in the future so you shouldn't use it", which I don't think is the case with plain promises.

I personally prefer the current version, since it's less verbose and more straightforward. But I wouldn't be against merging your change if there's a good reason that I'm not seeing.

**Comment by delaaxe** [comment]
> @delaaxe "deprecated" usually means "it will be removed in the future so you shouldn't use it", which I don't think is the case with plain promises.
> 
> 
> 
> I personally prefer the current version, since it's less verbose and more straightforward. But I wouldn't be against merging your change if there's a good reason that I'm not seeing.

Less verbose doesn't always mean more understandable and I find a regular try/catch more straightforward.

I agree it's not deprecated per se but languages evolve and it's good practice to use the latest ways of doing this.

I agree it's debatable though.

**Comment by fvictorio** [comment]
I understand your point but I think this is very subjective so, for now, I'd rather keep it as it is.

To clarify why I think the current version is simpler, this is what happens in my head when I read each one:

- "`main` returns a promise and, if it rejects, we print the error and finish the process with an exit code of 1"
- "we create an async IIFE and then we call and await `main` inside a try/catch; if `main` rejects, we catch and print the error and finish the process with an exit code of 1"

I understand though that if you have a different mental model, then the first version can actually be more confusing/harder to process. If we get more feedback suggesting that using an IIFE is clearer, we'll reconsider this.

**Pull request closed without merging**
