### PR TITLE
fix: reenabled tests

### PR DESCRIPTION
**Pull request by konarshankar07**
- [x] Because this PR includes a **bug fix**, relevant tests have been included.
- [ ] Because this PR includes a **new feature**, the change was previously discussed on an Issue or with someone from the team.
- [ ] I didn't do anything of this.

---

Fixed https://github.com/NomicFoundation/hardhat/issues/3448

### CODE REVIEW

**Comment by alcuadrado** [comment]
hey, thanks for this pr! Do you mind fixing the linting errors?

**Comment by konarshankar07** [comment]
@alcuadrado 

I fixed the lint issue

**Comment by alcuadrado** [comment]
Thanks! I added a changeset and will merge once I wake up 😴

**Comment by alcuadrado** [comment]
Done! Thanks a ton, @konarshankar07 🙌

**Comment by konarshankar07** [comment]
Thanks @alcuadrado for merging my first blockchain PR and looking forward to involve more into the community :)

**Pull request merged**
