### PR TITLE
Handle large JSON payloads

### PR DESCRIPTION
**Pull request by Dzejkop**
- [ ] Because this PR includes a **bug fix**, relevant tests have been included.
- [ ] Because this PR includes a **new feature**, the change was previously discussed on an Issue or with someone from the team.
- [x] I didn't do anything of this.

---

### CODE REVIEW

**Comment by alcuadrado** [comment]
Hey @Dzejkop, this PR is interesting, but can you give more info on the motivation behind it? When did you encounter a problem with the existing code?

Thanks!

**Comment by Dzejkop** [comment]
@alcuadrado sure, it's the same case as https://github.com/NomicFoundation/hardhat/issues/2165.

We're working on a private depoloyment with large limits for contract size. We encountered an error with the `JSON.stringify` method which would crash if the contract was too large.

**Comment by fvictorio** [comment]
Not stale

**Comment by citizen-stig** [comment]
@fvictorio Could you please re-open it?

**Comment by fvictorio** [comment]
Hey @Dzejkop, I'm (finally) looking into this PR, and something I would like to do is to actually test it in a scenario that hits the `JSON.stringify`/`JSON.parse` limits.

I tried to create some synthetic examples with a lot of data, but I made solc crash while compiling those. Do you have an example of a scenario where this happens?

**Comment by citizen-stig** [comment]
Hello @fvictorio , there's a repo with crafted example: https://github.com/citizen-stig/hardhat-large-contracts-compilation

I've just checked it with commands from READM.md and it reproduces the issue.

Please let me know if you have been able to reproduce it.

**Comment by citizen-stig** [comment]
Also details are available in the corresponding issue: https://github.com/NomicFoundation/hardhat/issues/2165

**Comment by fvictorio** [comment]
Thanks a lot @citizen-stig, I thought I had seen a reproduction repo in some issue but couldn't find it :man_facepalming:

**Comment by fvictorio** [comment]
Oh, I see. I couldn't reproduce this because it's actually fixed in the latest versions, which save the build info files in a more piece-wise way. We did that for performance reasons, but as a side-effect, it fixed #2165. That's also why there are a lot of merge conflicts in this PR.

I'm going to close this PR now. Sorry for throwing away your work @Dzejkop :disappointed: But the alternative here is to do this from scratch, and that also means adding a new dependency, which we normally try not to do.

@gitpoap-bot @Dzejkop deserves a gitpoap

**Comment by Dzejkop** [comment]
Thanks for the fix @fvictorio!

And thanks for keeping track of this @citizen-stig

**Pull request closed without merging**
