### PR TITLE
Add support for Cronoscan and BTTCScan

### PR DESCRIPTION
**Pull request by 0xV4L3NT1N3**

### CODE REVIEW

**Comment by fvictorio** [comment]
Hi @0xV4L3NT1N3, thanks for sending this.

Can you please take a look at step 5 [here](https://github.com/NomicFoundation/hardhat/blob/master/packages/hardhat-etherscan/CONTRIBUTING.md)? We need that to validate that everything works in the new chains.

**Comment by 0xV4L3NT1N3** [comment]
Funded address `0x4444c3F7D7d3153Dc0773C31ae10cf9B5495d4Bb`, listing the available RPCs below 

Cronos Mainnet : https://evm-cronos.crypto.org/
BTTC Mainnet : https://rpc.bt.io/
BTTC Testnet : https://pre-rpc.bt.io

**Comment by softwarearchaeologist** [comment]
Any update on merging this?

**Comment by fvictorio** [comment]
Still relevant.

Sorry for the delay guys, we'll get this merged this week.

**Comment by fvictorio** [comment]
Hi @0xV4L3NT1N3, thanks a lot for opening this PR.

We are going to stop adding networks to the core of `hardhat-etherscan`. Instead of that, we are adding support for setting custom explorers ([PR](https://github.com/NomicFoundation/hardhat/pull/2661)).

You can try this right now by installing `@nomiclabs/hardhat-etherscan@rc` and then modifying your config like this:

```js
etherscan: {
  apiKey: {
    cronos: "your-api-key",
    bttc: "your-api-key",
    bttcTestnet: "your-api-key",
  },
  customChains: [{
    network: "cronos",
    chainId: 25,
    urls: {
      apiURL: "https://api.cronoscan.com/api",
      browserURL: "https://cronoscan.com/",
    },
  }, {
    network: "bttc",
    chainId: 199,
    urls: {
      apiURL: "https://api.bttcscan.com/api",
      browserURL: "https://bttcscan.com/",
    },
  }, {
    network: "bttcTestnet",
    chainId: 1028,
    urls: {
      apiURL: "https://api-testnet.bttcscan.com/api",
      browserURL: "https://testnet.bttcscan.com/",
    },
  }]
}
```

The `customChains` part can be packaged in a plugin for others to use, if you are interested. Check [this example](https://github.com/fvictorio/hardhat-custom-chain-plugin-example) to learn how.

**Pull request closed without merging**
