### PR TITLE
1 new plugin, 1 plugin upgraded

### PR DESCRIPTION
**Pull request by 3obby**
minor addition to hardhat-storage-layout (now hardhat-storage-layout-json), (added .json file output), added HRE extension 'getHash' in new plugin "hardhat-generate-storage-namespace" to generate unique storage namespaces with automation.

- [x] I didn't do anything of this.

### CODE REVIEW

**Comment by fvictorio** [comment]
I'm not super comfortable with replacing a plugin with a fork, unless the original authors are ok with that. Otherwise, I would just add it as a new plugin.

Also, can you fix the linter issues? It's almost surely just a matter of formatting the plugins file.

**Comment by 3obby** [comment]
updates to my code:
-fixed formatting for prettier
-updated storage-namespace plugin to match [erc-7201 draft](https://eips.ethereum.org/EIPS/eip-7201)

for sure, I get that. I added that .json update to help in my progress with automation, but decided to fork and upgrade it for the community after noticing [the dormant pull request in their repo which adds this functionality](https://github.com/aurora-is-near/hardhat-storage-layout/pulls). I propose to give the original authors the credit for their work but also improve the plugin to help others that would benefit from more than just a cli readout of the data.

**Comment by 3obby** [comment]
I'd be happy to make separate pull requests for these and add them as new plugins, but also if the Aurora team wanted to fork and replace mine in turn, I'd be happy to expect that as well :)

**Comment by fvictorio** [comment]
> I'd be happy to make separate pull requests for these and add them as new plugins

Just updating this PR so that it adds your plugin instead of replacing the existing one should be fine!

**Comment by 3obby** [comment]
You got it! Thanks for being patient with me, fairly new to interacting with other repos :)

**Review by fvictorio — APPROVED** [review]

**Comment by fvictorio** [comment]
No problem at all, thanks for sending this!

**Pull request merged**
