### PR TITLE
Fix #1978 - ability to deploy to networks behind a corporate proxies

### LINKED ISSUE #1978: Add the ability to deploy to networks behind a Corporate HttpProxy
# SUMMARY

Hi everyone

Being behind a Corporate HttpProxy, I'd like to add the feature to deploy/interact with networks by using standard environment variables : `HTTPS_PROXY` or `HTTP_PROXY` .

This feature is really similar to https://github.com/nomiclabs/hardhat/pull/1291.

 # How to reproduce
```
# be behind a httpproxy
export HTTPS_PROXY=http://proxy.com
npx hardhat run --network external-network scripts/deploy.js
# Fail as not reachable
```
# Expected Result
```
# be behind a httpproxy
export HTTPS_PROXY=http://proxy.com
npx hardhat run --network external-network scripts/deploy.js
# Deploy Great Success !!!!
```

### PR DESCRIPTION
**Pull request by umakanth-fmr**
- [x] Because this PR includes a **bug fix**, relevant tests have been included.
- [ ] Because this PR includes a **new feature**, the change was previously discussed on an Issue or with someone from the team.
- [] I didn't do anything of this.

---
This PR addresses the issue with connecting to 3rd party networks behind corporate proxy. Currently undici Pool's does not support proxy. (https://github.com/nodejs/undici/issues/1270). 

We patched our local harhat to make it work. 

Relevant issues on hardhat issue tracker.

https://github.com/NomicFoundation/hardhat/issues/1978

### CODE REVIEW

**Comment by umakanth-fmr** [comment]
Pinging @fvictorio

**Comment by bolabola** [comment]
same error!!

**Comment by umakanth-fmr** [comment]
> same error!!

What is the error ?

**Comment by bolabola** [comment]
> > same error!!
> 
> What is the error ?
try this int hardhat.config.ts
` import { setGlobalDispatcher, ProxyAgent, Agent } from "undici";
 const proxyAgent = new ProxyAgent("http://127.0.0.1:1087");
 setGlobalDispatcher(proxyAgent);`

**Comment by umakanth-fmr** [comment]
GlobalDispatcher does not work on specific proxies. This PR looks at HTTP_PROXY/HTTPS_PROXY and it sets ProxyAgent for connection. undici connection pools does not support proxy yet.

**Comment by umakanth-fmr** [comment]
Any update on this PR @fvictorio ?

**Comment by fvictorio** [comment]
Hey @umakanth-fmr, I haven't had time to review this yet, sorry :disappointed:

I skimmed the PR's code and it looks good, but since this is a very sensitive change, I'll need to make a careful review before merging it.

**Comment by fvictorio** [comment]
Hey @umakanth-fmr, I ended up going for a somewhat different approach in https://github.com/NomicFoundation/hardhat/pull/3432. The main difference is that I'm using a single environment variable, `http_proxy`. I also implemented better support for that variable in Hardhat core.

I'm going to close this PR in favor of that one. Thanks again and sorry for not merging yours.

**Comment by fvictorio** [comment]
@gitpoap-bot @umakanth-fmr deserves a gitpoap

**Pull request closed without merging**
