### PR TITLE
Minimally patch the viaIR issue for running unit tests

### PR DESCRIPTION
**Pull request by jflatow**
This minimally patches the viaIR issue for a particular case where we are encountering it.

I believe this is also addresses the cause of #2115.

### CODE REVIEW

**Comment by jflatow** [comment]
> This PR was marked as stale because it didn't have any activity in the last 30 days. Please excuse us if we didn't have enough time to review it and get it merged. If you are still interested in getting these changes applied, please leave a comment indicating so. Otherwise, it will be closed in 7 days.

Please don't close until fixed!

**Comment by jflatow** [comment]
> This PR was marked as stale because it didn't have any activity in the last 30 days. Please excuse us if we didn't have enough time to review it and get it merged. If you are still interested in getting these changes applied, please leave a comment indicating so. Otherwise, it will be closed in 7 days.

Please don't close until fixed!

**Comment by jflatow** [comment]
> This PR was marked as stale because it didn't have any activity in the last 30 days. Please excuse us if we didn't have enough time to review it and get it merged. If you are still interested in getting these changes applied, please leave a comment indicating so. Otherwise, it will be closed in 7 days.

Please don't close until fixed!

**Comment by drortirosh** [comment]
Any reason NOT to merge this issue? while it doesn't "fix" the stack trace, at least it makes normal revert-to-error mapping works correctly and not break tests needlessly, and show the proper revert reason.
I came up with the exact same problem (failed unittest) and almost exact same workaround...

**Comment by fvictorio** [comment]
Hey guys, I'm very sorry for not merging this sooner. I believe this will be fixed (at least partially) by https://github.com/NomicFoundation/hardhat/pull/3205, so I'm going to close this one. I hope we can release that change in the coming weeks and I'll try to remember to let you know here when it's released.

**Pull request closed without merging**
