### PR TITLE
[WIP] Upgrade undici and make sure to always set its timeout fields

### PR DESCRIPTION
**Pull request by alcuadrado**
This PR also bumps the timeout used by hardhat-vyper to download the compiler. This tiemout wasn't used, but it happened to match unidici's default, and that wasn't enough.

### CODE REVIEW

**Comment by alcuadrado** [comment]
UPDATE

I noticed that we weren't handling a timeout, which can happen when establishing a connection. It has to be handled in the agent, not per-request, so this fix is outdated.

I implemented the proper fix in the HTTP provider, but I think this really calls for a `@nomicfoundation/hardhat-utils` package.

**Comment by hawkofsky** [comment]
is this pr not merged yet?

**Comment by fvictorio** [comment]
Not yet, I'll try to prioritize it.

**Comment by insider89** [comment]
Why is this one closed? I still have time out issue

**Pull request closed without merging**
