### PR TITLE
fix: use custom address recovery for fake signature

### PR DESCRIPTION
**Pull request by agostbiro**
Make sure we're not trying to recover the address from fake signatures. Fixes https://github.com/NomicFoundation/edr/issues/294

### CODE REVIEW

**Review by Wodann — APPROVED** [review]
I think I would have solved this differently, but this fixes the issue for now.

The function `transaction_from_block` can return the `ExecutableTransaction` which includes the from-address, voiding the need for recovery.

Something we should wonder is whether the concept of faking a transaction should be incorporated in the raw transaction type? This PR does so now, which I'm not a fan of.
A limiting factor atm is that we don't have a way of expressing that an `Address` is a valid Ethereum address.

E.g. it's currently still possible that someone uses a JSON-RPC client with fake transactions for testing, which would result in the recovery of an invalid Ethereum address.

I'll approve to expedite the merging process, but if you agree with the above, I'd prefer a minimal change to use the `ExecutionTransaction` (which already contains the correct address) and to revisit this discussion when we deal with https://github.com/NomicFoundation/edr/issues/260

**Comment by fvictorio** [comment]
> Something we should wonder is whether the concept of faking a transaction should be incorporated in the raw transaction type?

I don't think it should.

**Comment by agostbiro** [comment]
Thanks for thinking deeply about this  @Wodann! I'm answering between the lines below.

> Something we should wonder is whether the concept of faking a transaction should be incorporated in the raw transaction type? This PR does so now, which I'm not a fan of.

Faking a transaction is already incorporated into the raw transaction type: https://github.com/NomicFoundation/hardhat/blob/f6eb9365fdc23033f41a8ff7744c9398c8e2459f/crates/edr_eth/src/transaction/request.rs#L103

The source of the bug is that this is not taken into account when doing recovery which this PR fixes.

> A limiting factor atm is that we don't have a way of expressing that an Address is a valid Ethereum address.

> E.g. it's currently still possible that someone uses a JSON-RPC client with fake transactions for testing, which would result in the recovery of an invalid Ethereum address.

I don't follow either, sorry. Please elaborate :)

> The function `transaction_from_block` can return the `ExecutableTransaction` which includes the from-address, voiding the need for recovery. https://github.com/NomicFoundation/hardhat/pull/4911 shows my intended solution.

That's a good idea, but it still leaves `SignedTransaction::recover` in a broken state, so this bug is bound to reoccur in the future unless we fix that.


> I'll approve to expedite the merging process, but if you agree with the above, I'd prefer a minimal change to use the ExecutionTransaction (which already contains the correct address) and to revisit this discussion when we deal with https://github.com/NomicFoundation/edr/issues/260

The right way to handle this imo would be to have two signed transaction types: `SignedTransaction` and `FakeSignedTransaction` (or possibly a `SignedTransaction<SignatureType>`), as that'd ensure at compile time (instead of the runtime check solution in this PR) that the recovery logic is appropriate for the signature method. 

But moving the check to compile time is a bigger change, hence the approach in this PR.

All in all, I'd prefer the solution in this PR over https://github.com/NomicFoundation/hardhat/pull/4911 as while the latter fixes the immediate problem, it doesn't prevent it from reoccurring.

**Comment by Wodann** [comment]
> The right way to handle this imo would be to have two signed transaction types: SignedTransaction and FakeSignedTransaction (or possibly a SignedTransaction<SignatureType>), as that'd ensure at compile time (instead of the runtime check solution in this PR) that the recovery logic is appropriate for the signature method.

I agree with this. The `SignedTransaction<SignatureType>` would allow us to re-use as much of the data as possible.

> All in all, I'd prefer the solution in this PR over https://github.com/NomicFoundation/hardhat/pull/4911 as while the latter fixes the immediate problem, it doesn't prevent it from reoccurring.

It's unnecessary to use `recover()` given that we already know the `Address` when we call it. So at the very least we should merge both solutions; given that they solve different things.

**Pull request merged**
