### PR TITLE
Support chains that don't include a totalDifficulty block field

### PR DESCRIPTION
**Pull request by tinybike**
- [x] Because this PR includes a **new feature**, the change was previously discussed on an Issue or with someone from the team.

---

Resolves nomiclabs/hardhat#2106.  Wanted to go ahead and send in the PR while I was thinking of it, but I'm not sure this belongs in hardhat proper.  If you guys don't think so please feel free to just close.

### CODE REVIEW

**Comment by tinybike** [comment]
It's 100% up to you guys.  If you feel like this belongs in hardhat, sure, go for it.  Otherwise, feel free to close it.

**Comment by misterjame** [comment]
+1 trying to run moonbeam/moonriver on hardhat and need this fix

**Comment by yaojiach** [comment]
+1. In the meantime, any suggested workaround?

**Comment by timbrinded** [comment]
Hi @alcuadrado is this still in the pipeline?

**Comment by fvictorio** [comment]
Hi folks, sorry for the (very, very) late response.

I think the way to go here is to close this PR and open a new issue with this feature request, to discuss potential approaches and to gauge how much interest there is on this. The current implementation is a bit too hackish, so it's unlikely that we'll merge it. And since this is an old PR, I'd rather start over here.

I know that it sucks to get a response many months later just to get the PR closed, sorry again about that :disappointed:

**Comment by tinybike** [comment]
No worries @fvictorio, yes this was hackish af, I'm not surprised you don't want this silliness in hardhat proper haha

**Pull request closed without merging**
