### PR TITLE
fix: remove hardfork restriction on eth_getLogs

### PR DESCRIPTION
**Pull request by Wodann**
Fixes https://github.com/NomicFoundation/edr/issues/361

### CODE REVIEW

**Review by agostbiro — APPROVED** [review]
I couldn't find a hardfork restriction for `eth_getLogs` in the EthereumJS branch, so I agree that the right move is to remove it 👍

**Comment by Wodann** [comment]
I added a test to validate it, for completeness.

**Comment by jeremyjams** [comment]
Hello @Wodann thank you for the fix! @fvictorio I'm facing this issue, could release this work in a patch :pray: (2.21.1 or 2.22.3) ?

**Comment by Wodann** [comment]
> Hello @Wodann thank you for the fix! @fvictorio I'm facing this issue, could release this work in a patch :pray: (2.21.1 or 2.22.3) ?
> 

You're most welcome.

We haven't released a new version of hardhat yet, but you can force the EDR dependency to be upgraded by removing the lockfile constraint. That should ensure that Hardhat's underlying EDR dependency is updated to the latest :)

**Comment by jeremyjams** [comment]
Smart, thanks :sunglasses: !

**Pull request merged**
