### PR TITLE
feat: debug trace call

### PR DESCRIPTION
**Pull request by agostbiro**
Add EDR support for `debug_traceCall`. Please note that the base branch is https://github.com/NomicFoundation/hardhat/pull/4410.

### CODE REVIEW

**Review by Wodann — APPROVED** [review]

**Comment by Wodann** [comment]
The code looks good.

Can you just fix the linter error before merging?

**Comment by agostbiro** [comment]
> The code looks good.
> 
> Can you just fix the linter error before merging?

Thanks, do you mean [this lint?](https://github.com/NomicFoundation/hardhat/actions/runs/6396555783/job/17362595084) It seems to be [failing](https://github.com/NomicFoundation/hardhat/actions/runs/6341093418/job/17223954798?pr=4410) in the base branch as well and I'm not sure what to do about it.

**Comment by Wodann** [comment]
Don't worry about it then 👍

**Comment by agostbiro** [comment]
> Don't worry about it then 👍

Ok, I merged the base branch and the lint error seems to be fixed now, but there are a bunch provider test errors that are unrelated to this PR I think. Could you have a look at them @Wodann and merge the branch if you think they're ok?

**Pull request merged**
